// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoftHub.API.Data;

#nullable disable

namespace SoftHub.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoftHub.API.Models.ActivityLog", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Action").IsRequired().HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").IsRequired().HasColumnType("text");
                b.Property<int>("LeadId").HasColumnType("integer");
                b.Property<string>("NewValue").HasColumnType("text");
                b.Property<string>("OldValue").HasColumnType("text");
                b.Property<int?>("UserId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("LeadId");
                b.HasIndex("UserId");
                b.ToTable("ActivityLogs");
            });

            modelBuilder.Entity("SoftHub.API.Models.Lead", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int?>("AssignedToId").HasColumnType("integer");
                b.Property<string>("CompanyName").IsRequired().HasColumnType("text");
                b.Property<string>("CompanySize").IsRequired().HasColumnType("text");
                b.Property<string>("ContactPersonName").IsRequired().HasColumnType("text");
                b.Property<string>("ContactPersonPosition").IsRequired().HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasColumnType("text");
                b.Property<string>("Industry").IsRequired().HasColumnType("text");
                b.Property<string>("InterestLevel").IsRequired().HasColumnType("text");
                b.Property<DateTime?>("LastContactedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Location").IsRequired().HasColumnType("text");
                b.Property<string>("NextFollowUpDate").HasColumnType("text");
                b.Property<string>("Phone").IsRequired().HasColumnType("text");
                b.Property<decimal>("PotentialValue").HasColumnType("numeric(18,2)");
                b.Property<string>("Source").IsRequired().HasColumnType("text");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("AssignedToId");
                b.ToTable("Leads");
            });

            modelBuilder.Entity("SoftHub.API.Models.Note", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("AuthorId").HasColumnType("integer");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("LeadId").HasColumnType("integer");
                b.Property<string>("Text").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("AuthorId");
                b.HasIndex("LeadId");
                b.ToTable("Notes");
            });

            modelBuilder.Entity("SoftHub.API.Models.RefreshToken", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone");
                b.Property<bool>("IsRevoked").HasColumnType("boolean");
                b.Property<string>("Token").IsRequired().HasColumnType("text");
                b.Property<int>("UserId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("RefreshTokens");
            });

            modelBuilder.Entity("SoftHub.API.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasColumnType("text");
                b.Property<string>("FullName").IsRequired().HasColumnType("text");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("Role").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
                b.HasData(new {
                    Id = 1, FullName = "Admin User", Email = "admin@softhub.io",
                    PasswordHash = "$2a$11$rBnqhGLTkHKMQvkKp5Q5.OqHJhm3lfNlTRnVfJmvJgpJmZm6RYXS2",
                    Role = "Admin", IsActive = true,
                    CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                });
            });

            modelBuilder.Entity("SoftHub.API.Models.ActivityLog", b =>
            {
                b.HasOne("SoftHub.API.Models.Lead", "Lead").WithMany("Activities")
                    .HasForeignKey("LeadId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("SoftHub.API.Models.User", "User").WithMany()
                    .HasForeignKey("UserId").OnDelete(DeleteBehavior.SetNull);
            });

            modelBuilder.Entity("SoftHub.API.Models.Lead", b =>
            {
                b.HasOne("SoftHub.API.Models.User", "AssignedTo").WithMany("AssignedLeads")
                    .HasForeignKey("AssignedToId").OnDelete(DeleteBehavior.SetNull);
            });

            modelBuilder.Entity("SoftHub.API.Models.Note", b =>
            {
                b.HasOne("SoftHub.API.Models.User", "Author").WithMany("Notes")
                    .HasForeignKey("AuthorId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("SoftHub.API.Models.Lead", "Lead").WithMany("Notes")
                    .HasForeignKey("LeadId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("SoftHub.API.Models.RefreshToken", b =>
            {
                b.HasOne("SoftHub.API.Models.User", "User").WithMany()
                    .HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
